package com.shop_manager.ui.enums;

public enum ScreenName {
    MAIN_SCREEN,

    MANAGE_SCREEN,

    MANAGE_PRODUCTS_SCREEN,
    CREATE_PRODUCT_SCREEN,
    VIEW_ALL_PRODUCTS_SCREEN,
    UPDATE_PRODUCT_SCREEN,
    DELETE_PRODUCT_SCREEN,

    MANAGE_CASHIERS_SCREEN,
    CREATE_CASHIER_SCREEN,
    VIEW_ALL_CASHIERS_SCREEN,
    UPDATE_CASHIER_SCREEN,
    DELETE_CASHIER_SCREEN,

    MANAGE_STORES_SCREEN,
    CREATE_STORE_SCREEN,
    VIEW_ALL_STORES_SCREEN,
    UPDATE_STORE_SCREEN,
    DELETE_STORE_SCREEN,

    RECEIPT_LOADER_SCREEN,
    RECEIPT_RENDER_SCREEN
}
